### PR TITLE
Add remove source file option

### PR DESCRIPTION
**Pull request by dferrand**
### Changes

Add Remove source file option in source physical file contextual menu.

Addresses #30.

### Checklist

* [x] have tested my change
* [ ] updated relevant documentation
* [x] Remove any/all `console.log`s I added
* [x] eslint is not complaining
* [x] have added myself to the contributors' list in the README

### CODE REVIEW

**Comment by worksofliam** [comment]
Hey @dferrand - this is awesome.

I am sorry, I just merged a PR into master and think I caused a conflict. Can you check those out, and we'll get your stuff merged in!

**Comment by dferrand** [comment]
Conflict should be fixed now.

**Comment by worksofliam** [comment]
Thank you @dferrand! Just going to do some testing on my end and I will let you know within a few minutes.

**Comment by worksofliam** [comment]
LGTM! This one is getting merged and deployed in 0.1.1.

Thank you @dferrand!

**Pull request merged**
