### PR TITLE
starter documentation

### PR DESCRIPTION
**Pull request by barrettotte**
For now I created some placeholder documentation using Docsify to start on #12 .

I deployed the GitHub Pages on my fork at https://barrettotte.github.io/code-for-ibmi/#/ if you'd like a preview.

I put everything on a single markdown file so that it was an easier experience scrolling through the documentation.
But, if there are larger topics Docsify provides the mechanism for separate pages of documentation via ```docs/_sidebar.md```

I just slapped this together on my work break, so it definitely needs some improvement.
I know the settings descriptions need some work for sure.

Let me know what you think and if you have any suggestions. 

If you are looking for just a built static site from markdown, another option may have to be used.
Docsify uses VueJs in the background to fetch/render markdown files to the client. Therefore, it requires JavaScript enabled in browser which some people (understandably) don't enjoy.

### CODE REVIEW

**Comment by worksofliam** [comment]
Wow, this is really beautiful! Thank you very much.

I really like what you have done here. I am going to do some reviewing today, but my quick skim didn't show many problems if any.

**Comment by worksofliam** [comment]
@barrettotte Let's say we merge this - is the only part we really have to maintain the README.md? That sounds pretty easy.

Not only are you creating a solid base, you're also making it way easier for others to contribute.

**Comment by barrettotte** [comment]
@worksofliam That's correct, ```docs/README.md``` is the primary source. 

I agree I think the single README.md would make it very simple for someone to go in and update documentation without any headache.

If for some reason say compiling needs a huge detailed page it could be separated into a separate markdown file like ```docs/pages/compile.md``` and then linked back to the main ```docs/README.md``` via ```docs/_sidebar.md```.
But, that shouldn't be needed for a while, if at all.

**Comment by worksofliam** [comment]
@barrettotte That's great. Thanks for clarifying that.

It's likely I will merge today (in a few hours.. got some errands to run), setup the GH Pages for the repo and then contribute a bunch to it myself.

Just in the last 2 hours we added visible buttons to the member browser (add & refresh) which I want to add to the docs.

Thanks for your hard work!

**Comment by barrettotte** [comment]
@worksofliam Nice, sounds good to me. Thanks!

**Comment by SJLennon** [comment]
While browsing around I found the **docs** folder.  Lots of very good info in there that I think would be helpful for new users.  

 I don't see any way to get to it from VSCODE, which is where I suspect most new users will be looking, and not in guthub.  It appear that the first level README.md is what shows up in VSCODE Extensions.  Is it possible to put a link there to the info in the docs folder?

(Sorry, I don't know enough about VSCODE extensions and the docsify documentation confuses me somewhat...)
@barrettotte @worksofliam

**Comment by worksofliam** [comment]
@SJLennon Yes. The formal link to the docs is https://halcyon-tech.github.io/code-for-ibmi/#/

Feel free to make a PR to add it somewhere in the readme, otherwise, I will get around to it later.

Thanks!

**Comment by SJLennon** [comment]
@worksofliam 
I've sent in a PR.

**Pull request merged**
